blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/lucas75-labs/agile-multiple-teams/discussions
    about: If you have any questions or need help, please start a discussion.
