blank_issues_enabled: false
contact_links:
  - name: Discussões e Debates
    url: https://github.com/lucas75-labs/agile-multiple-teams/discussions
    about: Ponto de partida
  - name: Backlog do Time Abc
    url: https://github.com/orgs/lucas75-labs/projects/1
    about: Acesse aqui para adicionar algo diretamente no backlog do Time Abc.
  - name: Backlog do Time Cde
    url: https://github.com/orgs/lucas75-labs/projects/2
    about: Aceesse aqui para adicionar algo diretamente no backlog do Time Cde.
  - name: Backlog do Time Efg
    url: https://github.com/orgs/lucas75-labs/projects/3
    about: Acessse aqui para adicionar algo diretamente no backlog do Time Efg.