blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/lucas75-labs/agile-multiple-teams/discussions
    about: If you have any questions or need help, please start a discussion.
  - name: Backlog do Time Abc
    url: https://github.com/orgs/lucas75-labs/projects/1
    about: A
  - name: Backlog do Time Cde
    url: https://github.com/orgs/lucas75-labs/projects/2
    about: B
  - name: Backlog do Time Efg
    url: https://github.com/orgs/lucas75-labs/projects/3
    about: C